# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nicholas Wong | Melbourne, Australia
email: njwon4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nicholas is a software engineering student at Monash University.
  Passionate about writing clean, efficient and maintainable code,
  as well as working on and riding his motorcycle.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  NJWong

# Build settings
markdown: kramdown
