# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nicholas Wong | Web Developer | Melbourne, Australia
email: njwon4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A "Blog-folio" (part blog, part project portfolio) for Nicholas Wong.
  Nicholas is a Software Engineering student at Monash University in
  Melbourne, Australia. He is passionate about web development, from
  front-end to back-end and everything in between.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  NJWong

# Build settings
markdown: kramdown
